---
- name: build war
  hosts: build
  become: yes


  tasks:
  - name: Esure git and maven package is present
    apt:
      name: 
      - git
      - maven
      state: present

  - name: Clone repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/boxfuse-sample-java-war-hello

  - name: Build war
    shell: mvn -f /tmp/boxfuse-sample-java-war-hello package

  # Synchronization of src on the inventory host to the dest on the deligate host in pull mode
  - name:  Implement of transfer artifact to prodaction server
    synchronize:
      mode: pull
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
    delegate_to: 178.154.224.250


- name: production
  hosts: prod
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure tomcat service is started
    service:
     name: tomcat9
     state: started

